<?php
// generated by Poedit from wp-reset-core-tr_TR.po, do not edit directly 
return ['domain'=>NULL,'plural-forms'=>'nplurals=2; plural=(n != 1);','language'=>'tr_TR','pot-creation-date'=>'2025-06-04 18:52+0300','po-revision-date'=>'2025-06-04 18:52+0300','translation-revision-date'=>'2025-06-04 18:52+0300','project-id-version'=>'WP Reset Core','x-generator'=>'Poedit 3.6','messages'=>[]];
